# Generated by Django 5.0.3 on 2024-04-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('posting_url', models.URLField()),
                ('company_link', models.URLField()),
                ('company_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=10)),
                ('job_code', models.CharField(max_length=255)),
                ('experience_min', models.IntegerField()),
                ('experience_max', models.IntegerField()),
                ('education_level', models.CharField(max_length=10)),
                ('modification_timestamp', models.DateTimeField()),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
    ]
