# Generated by Django 5.0.3 on 2024-04-05 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('posting_url', models.URLField(blank=True, null=True)),
                ('company_link', models.URLField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('job_code', models.TextField(blank=True, null=True)),
                ('experience_min', models.IntegerField(blank=True, null=True)),
                ('experience_max', models.IntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('job_group', models.CharField(blank=True, max_length=10, null=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='postings.industry')),
            ],
        ),
    ]
