# Generated by Django 5.0.3 on 2024-04-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='industry',
            new_name='industry_id',
        ),
    ]
