# Generated by Django 5.0.3 on 2024-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='job_code',
            field=models.TextField(),
        ),
    ]
