# Generated by Django 5.0.3 on 2024-04-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_rename_industry_posting_industry_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='industry_id',
            new_name='industry',
        ),
    ]
