# Generated by Django 5.0.3 on 2024-04-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_alter_posting_job_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='education_level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posting',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posting',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posting',
            name='job_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posting',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posting',
            name='salary',
            field=models.CharField(max_length=255),
        ),
    ]
