# Generated by Django 5.0.3 on 2024-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_alter_posting_education_level_alter_posting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='company_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='posting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
