# Generated by Django 5.0.3 on 2024-04-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_rename_industry_id_posting_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
