# Generated by Django 5.0.3 on 2024-04-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_jobtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtype',
            old_name='type',
            new_name='code',
        ),
    ]
