# Generated by Django 5.0.3 on 2024-04-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_rename_type_jobtype_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='job_group',
        ),
    ]
