# Generated by Django 5.0.3 on 2024-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0006_remove_posting_job_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='postings', to='postings.skill'),
        ),
    ]
