# Generated by Django 5.0.3 on 2024-04-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0007_posting_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='job_code',
        ),
    ]
