# Generated by Django 5.0.3 on 2024-04-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0008_remove_posting_job_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='related_postings', to='postings.industry'),
        ),
    ]
