# Generated by Django 5.0.3 on 2024-04-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0009_posting_industries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='industry',
        ),
    ]
