# Generated by Django 5.0.3 on 2024-04-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0010_remove_posting_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='job_types',
            field=models.ManyToManyField(blank=True, related_name='postings', to='postings.jobtype'),
        ),
    ]
