# Generated by Django 5.0.3 on 2024-04-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0011_posting_job_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='job_type',
        ),
    ]
