# Generated by Django 5.0.3 on 2024-04-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0012_remove_posting_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
