# Generated by Django 5.0.3 on 2024-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0013_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
