# Generated by Django 5.0.3 on 2024-04-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0015_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='educations',
            field=models.ManyToManyField(blank=True, related_name='postings', to='postings.education'),
        ),
        migrations.AddField(
            model_name='posting',
            name='incomes',
            field=models.ManyToManyField(blank=True, related_name='postings', to='postings.income'),
        ),
        migrations.AddField(
            model_name='posting',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='postings', to='postings.region'),
        ),
    ]
