# Generated by Django 5.0.3 on 2024-04-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0017_remove_posting_education_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='id',
            new_name='code',
        ),
    ]
