# Generated by Django 5.0.3 on 2024-04-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0018_rename_id_skill_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience_min', models.IntegerField(blank=True, null=True)),
                ('experience_max', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('region1', models.CharField(blank=True, max_length=100)),
                ('region2', models.CharField(blank=True, max_length=100)),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
