# Generated by Django 5.0.3 on 2024-04-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0019_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='classification',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
