# Generated by Django 5.0.3 on 2024-04-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0020_jobposting_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='incomes',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='industries',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='job_types',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Posting',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
